# Welcome to Jekyll!
#

# Site settings
title: Android Iași
description: | 
  Let's grab a drink on Thursday and [talk about what's new](/events/android-drinks-1).
owner: Android Iași # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: just_contact_us_on_facebook
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://androidiasi.ro" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/androidiasi
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/groups/androidiasi/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:
permalink: none
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "events"
      type: "posts"
    values:
      layout: "event"

# Build settings
markdown: kramdown
#sass:
#  style: compressed
